### ISSUE TITLE
Can not create user - ModuleNotFoundError: No module named 'ee'

### ISSUE THREAD

**Issue by harryqt** [karambir/posthog-unlocked#2]
After installations complete, when trying to add a user, getting this error in latest tag.

```bash
root@debian-2cpu-4gb-sg-sin1:~/ph# docker compose exec web python manage.py create_staff_user --first-name ExampleUser --email user@example.com --password examplePassword --org-name ExampleOrg
{'event': ['Skipping service version requirements. This is dangerous and PostHog might not work as expected!'], 'timestamp': '2023-12-24T04:19:49.202247Z', 'logger': 'posthog.settings.service_requirements', 'level': 'warning', 'pid': 47, 'tid': 140416669910848}
2023-12-24T04:19:51.049810Z [warning  ] Skipping async migrations setup. This is unsafe in production! [posthog.apps] pid=47 tid=140416669910848
2023-12-24T04:19:51.061564Z [info     ] AXES: BEGIN LOG                [axes.apps] pid=47 tid=140416669910848
2023-12-24T04:19:51.062206Z [info     ] AXES: Using django-axes version 5.9.0 [axes.apps] pid=47 tid=140416669910848
2023-12-24T04:19:51.062345Z [info     ] AXES: blocking by IP only.     [axes.apps] pid=47 tid=140416669910848
Traceback (most recent call last):
  File "/code/manage.py", line 21, in <module>
    main()
  File "/code/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/python-runtime/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/python-runtime/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/python-runtime/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/python-runtime/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/code/posthog/management/commands/create_staff_user.py", line 21, in handle
    organization, team, user = User.objects.bootstrap(
  File "/code/posthog/models/user.py", line 82, in bootstrap
    user.join(organization=organization, level=OrganizationMembership.Level.OWNER)
  File "/code/posthog/models/user.py", line 232, in join
    self.update_billing_customer_email(organization)
  File "/code/posthog/models/user.py", line 265, in update_billing_customer_email
    from ee.billing.billing_manager import BillingManager  # avoid circular import
ModuleNotFoundError: No module named 'ee'
root@debian-2cpu-4gb-sg-sin1:~/ph#
```

**Comment by Lilneo786** [comment]
Install Missing Module: If 'ee' is a custom module or part of your project, make sure that it exists and is properly structured within your project directory. If it's part of an external library, check that you have installed the library correctly in your Docker container. You can use pip or pipenv to install Python packages within your container.

For example, to install a package named 'example-package,' you can add the following command to your Dockerfile:

`
RUN pip install example-package`

**Comment by harryqt** [comment]
@karambir Tried [8 months older](https://github.com/karambir/posthog-unlocked/pkgs/container/posthog-unlocked/90075014?tag=sha-1fee349) build where user creation script works fine.

Another issue is that I can't add website; can't get past billing. ☹️ Latest and old tags all have same issue. I think manual site ingestion script is required or this needs to patched.

**Comment by karambir** [comment]
Hey @Dibbyo456 ,

Thanks for noticing these. First issue can be fixed easily. I'll push the fix soon.

For second, I am trying to get the initial loader page stuck at billing/products behave like everything is already setup. New user/org flow is always tricky as posthog is updating their onboarding flow all the time.
